baseURL = 'https://blog.wang1zhen.com/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = "wang1zhen's Homepage"
theme = 'PaperMod'
enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe = true

[menu]
 [[menu.main]]
    name = "技术/Tech"
    pageRef = "/tech"
    weight = 1
 [[menu.main]]
    name = "学习/Learn"
    pageRef = "/learn"
    weight = 2
 [[menu.main]]
    name = "关于/About"
    pageRef = "/about"
    weight = 10

[params.homeInfoParams]
Title = "Stay Awhile and Listen.<br>英雄请留步，且听我一言。"
Content = ""

[[params.socialIcons]]
name = "github"
url = "https://github.com/wang1zhen/"

[params]
  env = "production"
  description = "wang1zhen 的个人博客，包括各种Linux、日语学习和物理相关的读书笔记等。"
  author = ["wang1zhen"]
  keywords = ["linux", "日语", "物理", "arch", "debian", "zfs", "blog"]
  ShowReadingTime = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  showtoc = true
  tocopen = true
  mainSections = ["tech", "learn"]

[params.assets]
  favicon = "favicon.ico"
  favicon16x16 = "favicon-16.png"
  favicon24x24 = "favicon-24.png"
  favicon32x32 = "favicon-32.png"
  favicon48x48 = "favicon-48.png"
  favicon64x64 = "favicon-64.png"
  favicon96x96 = "favicon-96.png"
  favicon128x128 = "favicon-128.png"
  favicon256x256 = "favicon-256.png"
  apple_touch_icon = "favicon-256.png"
